POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description" : "Esse é o primeiro video",
    "duration" : 180
}

###

GET  http://localhost:3333/videos

###

PUT http://localhost:3333/videos/4953a7d1-2230-41fa-bd87-f154917275b5
Content-Type: application/json

{
    "title": "Video 02",
    "description" : "Esse é o primeiro video",
    "duration" : 180
}

###

DELETE http://localhost:3333/videos/d1f35e53-fc1f-4df3-ab04-a55ba3f50754